# Site Settings
baseurl: "/owenhuang.github.io" # the subpath of your site, e.g. /blog
url: "https://h6kplus.github.io" # the base hostname & protocol for your site, 

# Features Setting
# Turn subpages on or off
publications: True
presentations: True
blog: True

# Language of the website
lang: en

# Search engine optimization settings
title: Yidong Huang
tagline: 
description: 
author: Yidong Huang
twitter:
  username: owenhunag117
  card: 
logo: /assets/img/avatar.jpg
social:
  name: Yidong Huang
  links:
    - https://twitter.com/owenhuang117
    - https://github.com/h6kplus
locale: en_GB

# Page Settings
theme_settings:
  title: Grape Academic Theme

  experience_title: EDUCATION
  interests_title: RESEARCH EXPERIENCE
  skills_title: SKILLS
  awards_title: RESEARCH INTERESTS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Me
  first_name: [Myself, M.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
